name: datadog-test-report-action
description: Send test reports to Datadog

inputs:
  junit-xml-path:
    description: Glob pattern to the JUnit XML file(s)
    required: true
  datadog-api-key:
    description: Datadog API key
    required: false
  datadog-site:
    description: Datadog site
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
